version: "3.8"

services:
  front:
    build: .
    image: hello-graphql-front
    container_name: front
    command: sh run.sh
    ports:
      - 8000:8000
    volumes:
      - .:/code
    environment:
      - PORT=8000
      - REACT_APP_BACKEND_HOST=http://localhost:3000
    networks:
      - default
      - hello-graphql

networks:
  hello-graphql:
    external: true
